import {
  AnimalInVivoBiodist,
  AnimalInVivoEfficacy,
  AnimalInVivoPk,
  AnimalInVivoStudy,
  ChemicalEntity,
  DrugChemicalRelation,
  DrugStatus,
  HumanActivity,
  InVitroMeasurement,
  InVitroStudy,
  RdcDrug,
} from "./types";

export const statusOptions: DrugStatus[] = [
  "Approved",
  "New Drug Application",
  "Phase 3",
  "Phase 2",
  "Phase 1",
  "Investigational New Drug",
  "Clinical candidate",
  "Investigative",
  "Terminated in phase 3",
  "Terminated in phase 2",
  "Terminated in phase 1",
  "Terminated",
];

export const drugs: RdcDrug[] = [
  {
    drugId: "RDC-0001",
    externalId: "EXT-0001",
    type: "Treatment",
    drugName: "Trastuzumab",
    drugSynonyms: "Herceptin; rhuMAb HER2",
    status: "Approved",
    mainPubmed: "12345678",
    mainDoi: "10.1000/j.jmb.2024.01.001",
    smiles: "C1=CC=...N2",
    structureImage: "/static/structures/RDC-0001.png",
    chebiId: "CHEBI:12345",
    pubchemCid: "176870",
    pubchemSid: "24871637",
    notes: "First monoclonal antibody targeting HER2.",
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    drugId: "RDC-0002",
    externalId: "EXT-0002",
    type: "Treatment",
    drugName: "Pertuzumab",
    drugSynonyms: "Omnitarg",
    status: "Phase 3",
    mainPubmed: "87654321",
    smiles: "C2=CC=...N3",
    structureImage: "/static/structures/RDC-0002.png",
    chebiId: "CHEBI:54321",
    pubchemCid: "24857091",
    pubchemSid: "36712890",
    createdAt: "2023-06-15T00:00:00Z",
    updatedAt: "2024-05-20T00:00:00Z",
  },
  {
    drugId: "RDC-0003",
    externalId: "EXT-0003",
    type: "Diagnosis",
    drugName: "Example Diagnostic RDC",
    drugSynonyms: "EDR",
    status: "Investigational New Drug",
    mainPubmed: "11223344",
    smiles: "C3=CC=...N4",
    structureImage: "/static/structures/RDC-0003.png",
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-09-05T00:00:00Z",
  },
];

export const chemicalEntities: ChemicalEntity[] = [
  {
    entityCategory: "compound",
    entityId: "CMP-001",
    name: "ColdCompound-X",
    synonyms: "CCX",
    smiles: "CC(=O)O",
    formula: "C10H12O3",
    structureImage: "/img/compound_struct.png",
    mol2dPath: "/mol/CMP-001_2d.mol",
    mol3dPath: "/mol/CMP-001_3d.mol",
    pubchemCid: "123456",
    inchi: "InChI=1S/...",
    inchikey: "ABCDEFG-HIJKL",
    iupacName: "IUPAC long name",
    molecularWeight: 1234.56,
    complexity: 88.1,
    heavyAtomCount: 42,
    hbondAcceptors: 5,
    hbondDonors: 2,
    rotatableBonds: 7,
    logp: 3.14,
    tpsa: 44.2,
    linkerType: null,
    radionuclideSymbol: null,
    radionuclideHalfLife: null,
    radionuclideEmission: null,
    radionuclideEnergy: null,
  },
  {
    entityCategory: "ligand",
    entityId: "LIG-001",
    name: "Ligand-A",
    logp: 2.1,
    tpsa: 61.2,
    linkerType: null,
    radionuclideSymbol: null,
    radionuclideHalfLife: null,
    radionuclideEmission: null,
    radionuclideEnergy: null,
  },
  {
    entityCategory: "linker",
    entityId: "LNK-001",
    name: "MC-Val-Cit-PABC",
    linkerType: "cleavable",
    logp: 1.7,
    tpsa: 55.1,
    radionuclideSymbol: null,
    radionuclideHalfLife: null,
    radionuclideEmission: null,
    radionuclideEnergy: null,
  },
  {
    entityCategory: "chelator",
    entityId: "CHT-001",
    name: "DOTA",
    logp: -1.1,
    tpsa: 75.4,
    radionuclideSymbol: null,
    radionuclideHalfLife: null,
    radionuclideEmission: null,
    radionuclideEnergy: null,
  },
  {
    entityCategory: "radionuclide",
    entityId: "RAD-001",
    name: "Lu-177",
    radionuclideSymbol: "Lu",
    radionuclideHalfLife: "6.7 days",
    radionuclideEmission: "Beta / Gamma",
    radionuclideEnergy: "0.497 MeV",
  },
  {
    entityCategory: "compound",
    entityId: "CMP-002",
    name: "ColdCompound-Y",
    synonyms: "CCY",
    smiles: "CC(=O)N",
    formula: "C12H14N2O2",
    structureImage: "/img/compound_struct_y.png",
    mol2dPath: "/mol/CMP-002_2d.mol",
    mol3dPath: "/mol/CMP-002_3d.mol",
    molecularWeight: 142.22,
    complexity: 65.4,
    heavyAtomCount: 36,
    hbondAcceptors: 6,
    hbondDonors: 1,
    rotatableBonds: 5,
    logp: 2.74,
    tpsa: 38.9,
    linkerType: null,
    radionuclideSymbol: null,
    radionuclideHalfLife: null,
    radionuclideEmission: null,
    radionuclideEnergy: null,
  },
  {
    entityCategory: "ligand",
    entityId: "LIG-002",
    name: "Ligand-B",
    logp: 2.0,
    tpsa: 60.0,
    linkerType: null,
    radionuclideSymbol: null,
    radionuclideHalfLife: null,
    radionuclideEmission: null,
    radionuclideEnergy: null,
  },
  {
    entityCategory: "linker",
    entityId: "LNK-002",
    name: "PEG4-Val-Cit",
    linkerType: "cleavable",
    logp: 1.2,
    tpsa: 49.0,
    radionuclideSymbol: null,
    radionuclideHalfLife: null,
    radionuclideEmission: null,
    radionuclideEnergy: null,
  },
  {
    entityCategory: "chelator",
    entityId: "CHT-002",
    name: "NOTA",
    logp: -0.6,
    tpsa: 80.3,
    radionuclideSymbol: null,
    radionuclideHalfLife: null,
    radionuclideEmission: null,
    radionuclideEnergy: null,
  },
  {
    entityCategory: "radionuclide",
    entityId: "RAD-002",
    name: "Ac-225",
    radionuclideSymbol: "Ac",
    radionuclideHalfLife: "10 days",
    radionuclideEmission: "Alpha",
    radionuclideEnergy: "5.8 MeV",
  },
  {
    entityCategory: "compound",
    entityId: "CMP-003",
    name: "ColdCompound-Z",
    synonyms: "CCZ",
    smiles: "C7H5N3O6",
    formula: "C7H5N3O6",
    structureImage: "/img/compound_struct_z.png",
    mol2dPath: "/mol/CMP-003_2d.mol",
    mol3dPath: "/mol/CMP-003_3d.mol",
    molecularWeight: 215.13,
    complexity: 97.5,
    heavyAtomCount: 21,
    hbondAcceptors: 7,
    hbondDonors: 0,
    rotatableBonds: 3,
    logp: 1.4,
    tpsa: 62.1,
    linkerType: null,
    radionuclideSymbol: null,
    radionuclideHalfLife: null,
    radionuclideEmission: null,
    radionuclideEnergy: null,
  },
  {
    entityCategory: "ligand",
    entityId: "LIG-003",
    name: "Ligand-C",
    logp: 1.5,
    tpsa: 54.8,
    linkerType: null,
    radionuclideSymbol: null,
    radionuclideHalfLife: null,
    radionuclideEmission: null,
    radionuclideEnergy: null,
  },
  {
    entityCategory: "linker",
    entityId: "LNK-003",
    name: "Azido-PEG3",
    linkerType: "clickable",
    logp: 0.8,
    tpsa: 70.1,
    radionuclideSymbol: null,
    radionuclideHalfLife: null,
    radionuclideEmission: null,
    radionuclideEnergy: null,
  },
  {
    entityCategory: "chelator",
    entityId: "CHT-003",
    name: "DFO",
    logp: -0.9,
    tpsa: 82.2,
    radionuclideSymbol: null,
    radionuclideHalfLife: null,
    radionuclideEmission: null,
    radionuclideEnergy: null,
  },
  {
    entityCategory: "radionuclide",
    entityId: "RAD-003",
    name: "Ga-68",
    radionuclideSymbol: "Ga",
    radionuclideHalfLife: "67.7 minutes",
    radionuclideEmission: "Positron",
    radionuclideEnergy: "1.90 MeV",
  },
];

export const drugChemicalRelations: DrugChemicalRelation[] = [
  { drugId: "RDC-0001", entityCategory: "compound", entityId: "CMP-001", relationRole: "active" },
  { drugId: "RDC-0001", entityCategory: "ligand", entityId: "LIG-001", relationRole: "active" },
  { drugId: "RDC-0001", entityCategory: "linker", entityId: "LNK-001", relationRole: "active" },
  { drugId: "RDC-0001", entityCategory: "chelator", entityId: "CHT-001", relationRole: "active" },
  { drugId: "RDC-0001", entityCategory: "radionuclide", entityId: "RAD-001", relationRole: "active" },
  { drugId: "RDC-0002", entityCategory: "compound", entityId: "CMP-002", relationRole: "active" },
  { drugId: "RDC-0002", entityCategory: "ligand", entityId: "LIG-002", relationRole: "active" },
  { drugId: "RDC-0002", entityCategory: "linker", entityId: "LNK-002", relationRole: "active" },
  { drugId: "RDC-0002", entityCategory: "chelator", entityId: "CHT-002", relationRole: "active" },
  { drugId: "RDC-0002", entityCategory: "radionuclide", entityId: "RAD-002", relationRole: "active" },
  { drugId: "RDC-0003", entityCategory: "compound", entityId: "CMP-003", relationRole: "active" },
  { drugId: "RDC-0003", entityCategory: "ligand", entityId: "LIG-003", relationRole: "active" },
  { drugId: "RDC-0003", entityCategory: "linker", entityId: "LNK-003", relationRole: "active" },
  { drugId: "RDC-0003", entityCategory: "chelator", entityId: "CHT-003", relationRole: "active" },
  { drugId: "RDC-0003", entityCategory: "radionuclide", entityId: "RAD-003", relationRole: "active" },
];

export const humanActivities: HumanActivity[] = [
  {
    drugId: "RDC-0001",
    clinicalTrialNumber: "NCT00000000",
    indication: "HER2+ breast cancer",
    patients: "n=120, female adults",
    dosage: "8 mg/kg loading, 6 mg/kg maintenance",
    frequency: "every 3 weeks",
    resultsDescription: "Significant improvement in progression-free survival.",
    purpose: "Assess efficacy in metastatic HER2+ breast cancer",
    clinicalEndpoint: "PFS",
    endpointPeriod: "12 months",
    efficacyDescription: "Improved ORR to 60%",
    adverseEventsSummary: "Grade 1-2 infusion reactions",
    securityIndicators: "Monitored LVEF quarterly",
  },
  {
    drugId: "RDC-0002",
    clinicalTrialNumber: "NCT11111111",
    indication: "Metastatic breast cancer",
    patients: "n=80",
    dosage: "420 mg",
    frequency: "every 3 weeks",
    resultsDescription: "Comparable efficacy to standard of care.",
    purpose: "Combination therapy with docetaxel",
    clinicalEndpoint: "ORR",
    endpointPeriod: "24 weeks",
    efficacyDescription: "ORR 54%",
    adverseEventsSummary: "Neutropenia, diarrhea",
    securityIndicators: "Cardiac monitoring required",
  },
  {
    drugId: "RDC-0003",
    clinicalTrialNumber: "NCT22222222",
    indication: "Neuroendocrine tumors",
    patients: "n=32",
    dosage: "200 MBq",
    frequency: "single administration",
    resultsDescription: "Early imaging shows high lesion uptake.",
    purpose: "Phase I dosimetry study",
    clinicalEndpoint: "Biodistribution",
    endpointPeriod: "72 hours",
    efficacyDescription: "Imaging contrast ratio > 6",
    adverseEventsSummary: "No serious adverse events",
    securityIndicators: "Renal function monitoring only",
  },
];

export const animalInVivoStudies: AnimalInVivoStudy[] = [
  { studyId: "STUDY-01", drugId: "RDC-0001", pmid: "33344455", doi: "10.1000/animal.01" },
  { studyId: "STUDY-02", drugId: "RDC-0001", pmid: "33344456", doi: "10.1000/animal.02" },
  { studyId: "STUDY-03", drugId: "RDC-0002", pmid: "33344457", doi: "10.1000/animal.03" },
  { studyId: "STUDY-04", drugId: "RDC-0003", pmid: "33344458", doi: "10.1000/animal.04" },
];

export const animalInVivoPkRecords: AnimalInVivoPk[] = [
  {
    studyRefId: "STUDY-01",
    pkAnimalModel: "Mouse xenograft",
    pkDosageSymbols: "≈",
    pkDosageValue: 5,
    pkDosageUnit: "mg/kg",
    pkDescription: "Biphasic clearance observed.",
    halfLife: "2.5h",
    pkImage: "/img/pk.png",
  },
  {
    studyRefId: "STUDY-03",
    pkAnimalModel: "Rat",
    pkDosageSymbols: "=",
    pkDosageValue: 10,
    pkDosageUnit: "mg/kg",
    pkDescription: "Stable plasma exposure.",
    halfLife: "3.8h",
  },
];

export const animalInVivoBiodistRecords: AnimalInVivoBiodist[] = [
  {
    studyRefId: "STUDY-01",
    biodistType: "Biodistribution",
    animalModel: "Mouse",
    dosageSymbols: "=",
    dosageValue: 10,
    dosageUnit: "MBq",
    metabolism: "Hepatic clearance",
    excretion: "Renal and biliary",
    detectionTime: "2h",
    tumorRetentionTime: "24h",
    tbrTumorBlood: 12.3,
    tbrTumorMuscle: 5.4,
    tbrTumorKidney: 2.1,
    tbrTumorSalivaryGlands: 1.1,
    tbrTumorLiver: 0.8,
    tbrTumorLung: 3.2,
    tbrTumorHeart: 4.5,
    biodistResultImage: "/img/biodist.png",
    biodistDescription: "Sustained tumor uptake with fast blood clearance.",
  },
  {
    studyRefId: "STUDY-04",
    biodistType: "Dosimetry",
    animalModel: "Rabbit",
    dosageSymbols: "≈",
    dosageValue: 15,
    dosageUnit: "MBq",
    metabolism: "Minimal metabolism",
    excretion: "Renal",
    detectionTime: "1h",
    tumorRetentionTime: "12h",
    tbrTumorBlood: 8.1,
    tbrTumorMuscle: 4.2,
    tbrTumorKidney: 3.5,
    tbrTumorSalivaryGlands: 1.8,
    tbrTumorLiver: 1.0,
    tbrTumorLung: 2.5,
    tbrTumorHeart: 3.1,
  },
];

export const animalInVivoEfficacyRecords: AnimalInVivoEfficacy[] = [
  {
    studyRefId: "STUDY-01",
    efficacyAnimalModel: "Mouse",
    efficacyDosageSymbols: "<",
    efficacyDosageValue: 10,
    efficacyDosageUnit: "MBq",
    efficacyDescription: "Tumor growth inhibition 75%",
    adverseReactions: "Mild body weight loss",
  },
  {
    studyRefId: "STUDY-03",
    efficacyAnimalModel: "Rat",
    efficacyDosageSymbols: "=",
    efficacyDosageValue: 5,
    efficacyDosageUnit: "mg/kg",
    efficacyDescription: "Tumor regression in 3/6 animals",
    adverseReactions: "Transient lethargy",
  },
];

export const inVitroStudies: InVitroStudy[] = [
  {
    inVitroId: "IV-01",
    drugId: "RDC-0001",
    studyOverview: "Affinity study against HER2-positive cell lines.",
    notes: "Used SPR and flow cytometry.",
  },
  {
    inVitroId: "IV-02",
    drugId: "RDC-0002",
    studyOverview: "Partition coefficient and stability in serum.",
  },
];

export const inVitroMeasurements: InVitroMeasurement[] = [
  {
    inVitroRefId: "IV-01",
    measurementCategory: "affinity",
    measurementType: "KD",
    measurementSymbols: "=",
    measurementValue: 0.12,
    measurementUnit: "nM",
    methodDescription: "Surface plasmon resonance",
  },
  {
    inVitroRefId: "IV-01",
    measurementCategory: "stability",
    measurementType: "Serum stability",
    measurementSymbols: "≈",
    measurementValue: 96,
    measurementUnit: "%",
    methodDescription: "Incubated at 37C for 72h",
  },
  {
    inVitroRefId: "IV-02",
    measurementCategory: "partition_coefficient",
    measurementType: "logP",
    measurementSymbols: "=",
    measurementValue: 3.14,
    methodDescription: "Octanol/water",
  },
  {
    inVitroRefId: "IV-02",
    measurementCategory: "stability",
    measurementType: "Serum stability",
    measurementSymbols: "=",
    measurementValue: 92,
    measurementUnit: "%",
    methodDescription: "Radio-HPLC analysis",
  },
];
